inputs:
  name: 
    description: 'Your name'
    default: 'No name provided'
  access_key:
    description: 'the access key'
  secret_access_key:
    description: 'the secret_acces_key'

runs:
  using: "composite"
  steps: 
    - run: echo Hello ${{ inputs.name }}.
      shell: bash
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.access_key }}
        aws-secret-access-key: ${{ inputs.secret_acces_key }}
        aws-region: us-west-2
    - name: S3 LS
      run: |
        aws s3 ls
      shell: bash  
