name: hello-world
on:
  workflow_call:
    inputs:
      who-to-greet:
        required: true
        type: string
    secrets:
      example-secret:
        required: true
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello-World
        run: echo "Hello ${{inputs.who-to-greet}}"
      - name: Reveal-Secret
        run: echo "The secret is '${{secrets.secret-phrase}}'"